version: 2
jobs:
  build:
    working-directory: ~/circulate
    docker:
      -image: python: 3.6.0
    steps:
      - checkout
      - run: echo 'hello world'

# version: 2
# jobs:
#   build:
#     working-directory: ~/circulate
#     docker:
#       -image: python: 3.6.0
#       environment:
#         FLASK_CONFIG: testing
#         TEST_DATABASE_URL:
#     steps:
#       - checkout
#       - run: echo 'hello world'

